[functions.sincronizar-projetos-qualidade]
verify_jwt = true

[functions.enviar-certificado]
verify_jwt = false

[functions.monday-revisores]
verify_jwt = false

[functions.certificados-fila-status]
verify_jwt = false

[functions.processar-certificados]
verify_jwt = false
