(function(){
"use strict";
let registros=[], filtrados=[];
const $=id=>document.getElementById(id);
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase();
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const chave=r=>[r.revisor_validador,r.id_ua||r.item_name,r.titulo,r.semestre_oferta].map(norm).join("|");
const gerados=()=>new Set(JSON.parse(localStorage.getItem("bi_certificados_gerados")||"[]"));
function salvarGerado(k){const s=gerados();s.add(k);localStorage.setItem("bi_certificados_gerados",JSON.stringify([...s]));}
function elegivel(x){return norm(x.status_validacao)==="validado" && !!String(x.revisor_validador||"").trim();}
function preparar(dados){const map=new Map();(dados||[]).filter(elegivel).forEach(x=>{const r={revisor_validador:x.revisor_validador||"",name:x.id_ua||x.titulo_ua||x.item_name||x.unidade_material||"",titulo:x.titulo||x.id_titulo||"",semestre_oferta:x.semestre_oferta||"",id_ua:x.id_ua||x.chave_ua||x.chave_material||""};const k=chave(r);if(!map.has(k))map.set(k,r)});registros=[...map.values()].sort((a,b)=>String(a.revisor_validador).localeCompare(String(b.revisor_validador),"pt-BR"));}
function filtros(){const q=norm($("certBusca")?.value),rev=$("certFiltroRevisor")?.value||"";filtrados=registros.filter(r=>(!rev||r.revisor_validador===rev)&&(!q||norm([r.revisor_validador,r.name,r.titulo,r.semestre_oferta].join(" ")).includes(q)));render();}
function render(){const body=$("certTabelaBody");if(!body)return;const gs=gerados();body.innerHTML=filtrados.length?filtrados.map((r,i)=>{const k=chave(r),g=gs.has(k);return `<tr><td><input class="cert-check" type="checkbox" data-i="${i}"></td><td>${esc(r.revisor_validador)}</td><td>${esc(r.name||"—")}</td><td>${esc(r.titulo||"—")}</td><td>${esc(r.semestre_oferta||"—")}</td><td><span class="cert-badge ${g?"gerado":""}">${g?"Gerado":"Pendente"}</span></td><td><div class="cert-row-actions"><button class="cert-mini-btn" data-gerar="${i}" type="button">Gerar PDF</button></div></td></tr>`}).join(""):'<tr><td colspan="7">Nenhum certificado elegível no filtro atual.</td></tr>';$("certKpiElegiveis").textContent=registros.length;$("certKpiRevisores").textContent=new Set(registros.map(r=>norm(r.revisor_validador))).size;$("certKpiGerados").textContent=registros.filter(r=>gs.has(chave(r))).length;atualizaSelecionados();}
function atualizaSelecionados(){if($("certKpiSelecionados"))$("certKpiSelecionados").textContent=document.querySelectorAll(".cert-check:checked").length;}
function popularRevisores(){const sel=$("certFiltroRevisor");if(!sel)return;const atual=sel.value;const vals=[...new Set(registros.map(r=>r.revisor_validador).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"));sel.innerHTML='<option value="">Todos os revisores</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("");sel.value=atual;}
function gerar(r){const bg=new URL("assets_certificado.png",location.href).href;const texto=`Certificamos que <strong>${esc(r.revisor_validador)}</strong> participou da criação e validação do material didático digital denominado Unidade de Aprendizagem <strong>${esc(r.name||"—")}</strong>, vinculada ao <strong>${esc(r.titulo||"—")}</strong>, concluída no período de <strong>${esc(r.semestre_oferta||"—")}</strong>, em conformidade com os parâmetros de qualidade e as diretrizes pedagógicas, técnicas e editoriais estabelecidas pela Ânima Educação.`;const w=window.open("","_blank");if(!w){alert("Permita pop-ups para gerar o certificado.");return;}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Certificado - ${esc(r.revisor_validador)}</title><style>@page{size:A4 landscape;margin:0}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;font-family:Arial,sans-serif}.page{width:297mm;height:210mm;position:relative;background:url('${bg}') center/100% 100% no-repeat}.texto{position:absolute;left:32mm;right:32mm;top:79mm;font-size:15.5pt;line-height:1.45;text-align:justify;color:#171717}.hint{position:fixed;right:12px;top:12px;background:#fff;border:1px solid #ddd;padding:8px 12px;border-radius:8px;font-size:12px}@media print{.hint{display:none}}</style></head><body><div class="page"><div class="texto">${texto}</div></div><div class="hint">Na janela de impressão escolha <b>Salvar como PDF</b>.</div><script>setTimeout(()=>window.print(),450)<\/script></body></html>`);w.document.close();salvarGerado(chave(r));setTimeout(render,600);}
function bind(){if(window.__certBind)return;window.__certBind=true;$("certBusca")?.addEventListener("input",filtros);$("certFiltroRevisor")?.addEventListener("change",filtros);$("certTabelaBody")?.addEventListener("click",e=>{const b=e.target.closest("[data-gerar]");if(b)gerar(filtrados[Number(b.dataset.gerar)]);});$("certTabelaBody")?.addEventListener("change",atualizaSelecionados);$("certCheckTodos")?.addEventListener("change",e=>{document.querySelectorAll(".cert-check").forEach(c=>c.checked=e.target.checked);atualizaSelecionados();});$("certSelecionarTodos")?.addEventListener("click",()=>{document.querySelectorAll(".cert-check").forEach(c=>c.checked=true);if($("certCheckTodos"))$("certCheckTodos").checked=true;atualizaSelecionados();});$("certGerarSelecionados")?.addEventListener("click",()=>{const idx=[...document.querySelectorAll(".cert-check:checked")].map(c=>Number(c.dataset.i));if(!idx.length){alert("Selecione ao menos um certificado.");return;}if(idx.length>1&&!confirm(`Serão abertas ${idx.length} janelas de impressão. O navegador pode solicitar permissão para pop-ups. Continuar?`))return;idx.forEach((i,n)=>setTimeout(()=>gerar(filtrados[i]),n*700));});}
window.atualizarCertificados=function(dados){preparar(dados);popularRevisores();filtrados=[...registros];bind();filtros();};
})();
