-- PROJETOS DA QUALIDADE - INSTALACAO COMPLETA DO BANCO
-- Execute este arquivo no SQL Editor do projeto Supabase:
-- xgtzyinfinjehxzojafn
--
-- O script e seguro para ser executado novamente: ele nao apaga dados.

create extension if not exists pgcrypto;

-- 1. Cada envio de planilha gera uma importacao auditavel.
create table if not exists public.pq_importacoes (
  id uuid primary key default gen_random_uuid(),
  nome_arquivo text not null,
  origem_url text,
  arquivo_hash text,
  usuario_email text,
  status text not null default 'processando',
  total_linhas integer not null default 0,
  projetos_inseridos integer not null default 0,
  projetos_atualizados integer not null default 0,
  tarefas_inseridas integer not null default 0,
  tarefas_atualizadas integer not null default 0,
  linhas_com_erro integer not null default 0,
  mensagem text,
  iniciado_em timestamptz not null default now(),
  finalizado_em timestamptz,
  constraint pq_importacoes_status_check
    check (status in ('processando', 'concluida', 'erro')),
  constraint pq_importacoes_total_linhas_check
    check (total_linhas >= 0),
  constraint pq_importacoes_arquivo_hash_check
    check (arquivo_hash is null or arquivo_hash ~ '^[a-f0-9]{64}$')
);

-- 2. Cadastro atual dos projetos recebidos do Ajure.
create table if not exists public.pq_projetos (
  id uuid primary key default gen_random_uuid(),
  azure_id text not null unique,
  nome text not null,
  status text,
  data_inicio date,
  data_fim date,
  sponsor text,
  esforco text,
  prioridade text,
  evidencia_original text,
  ativo boolean not null default true,
  presente_ultima_importacao boolean not null default true,
  ultima_importacao_id uuid references public.pq_importacoes(id)
    on delete set null,
  primeira_aparicao_em timestamptz not null default now(),
  ultima_aparicao_em timestamptz not null default now(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint pq_projetos_periodo_check
    check (data_inicio is null or data_fim is null or data_fim >= data_inicio)
);

-- 3. Cadastro atual das tarefas e dos Action Plans.
create table if not exists public.pq_tarefas (
  id uuid primary key default gen_random_uuid(),
  azure_id text not null unique,
  projeto_id uuid references public.pq_projetos(id)
    on delete set null,
  nome_projeto_origem text not null,
  tipo text not null,
  descricao text,
  status text,
  data_inicio date,
  data_fim date,
  sponsor text,
  ativo boolean not null default true,
  presente_ultima_importacao boolean not null default true,
  ultima_importacao_id uuid references public.pq_importacoes(id)
    on delete set null,
  primeira_aparicao_em timestamptz not null default now(),
  ultima_aparicao_em timestamptz not null default now(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint pq_tarefas_tipo_check
    check (tipo in ('Tarefa', 'Action Plan')),
  constraint pq_tarefas_periodo_check
    check (data_inicio is null or data_fim is null or data_fim >= data_inicio)
);

-- 4. Copia bruta de cada linha recebida, inclusive das linhas com erro.
create table if not exists public.pq_importacao_linhas (
  id bigint generated by default as identity primary key,
  importacao_id uuid not null references public.pq_importacoes(id)
    on delete cascade,
  numero_linha integer not null,
  nome_aba text,
  azure_id_original text,
  tipo_original text,
  projeto_original text,
  acao_original text,
  status_original text,
  dados_originais jsonb not null default '{}'::jsonb,
  processado boolean not null default false,
  erro_validacao text,
  criado_em timestamptz not null default now(),
  constraint pq_importacao_linhas_numero_check
    check (numero_linha > 0),
  constraint pq_importacao_linhas_unica
    unique (importacao_id, numero_linha)
);

-- 5. Historico do estado de cada projeto em cada importacao.
create table if not exists public.pq_projetos_snapshots (
  id bigint generated by default as identity primary key,
  projeto_id uuid not null references public.pq_projetos(id)
    on delete cascade,
  importacao_id uuid not null references public.pq_importacoes(id)
    on delete cascade,
  nome text not null,
  status text,
  data_inicio date,
  data_fim date,
  sponsor text,
  esforco text,
  prioridade text,
  registrado_em timestamptz not null default now(),
  constraint pq_projetos_snapshots_unico
    unique (projeto_id, importacao_id)
);

-- Indices usados pela funcao e pelos relatorios.
create index if not exists pq_importacoes_iniciado_em_idx
  on public.pq_importacoes (iniciado_em desc);

create index if not exists pq_importacoes_usuario_email_idx
  on public.pq_importacoes (usuario_email)
  where usuario_email is not null;

create unique index if not exists pq_importacoes_hash_concluida_uidx
  on public.pq_importacoes (arquivo_hash)
  where arquivo_hash is not null and status = 'concluida';

create index if not exists pq_projetos_nome_idx
  on public.pq_projetos (lower(nome));

create index if not exists pq_projetos_ultima_importacao_idx
  on public.pq_projetos (ultima_importacao_id);

create index if not exists pq_projetos_presentes_idx
  on public.pq_projetos (presente_ultima_importacao);

create index if not exists pq_tarefas_projeto_id_idx
  on public.pq_tarefas (projeto_id);

create index if not exists pq_tarefas_ultima_importacao_idx
  on public.pq_tarefas (ultima_importacao_id);

create index if not exists pq_tarefas_presentes_idx
  on public.pq_tarefas (presente_ultima_importacao);

create index if not exists pq_importacao_linhas_importacao_idx
  on public.pq_importacao_linhas (importacao_id);

create index if not exists pq_importacao_linhas_erros_idx
  on public.pq_importacao_linhas (importacao_id, processado);

create index if not exists pq_snapshots_importacao_idx
  on public.pq_projetos_snapshots (importacao_id);

-- Mantem atualizado_em correto nos upserts.
create or replace function public.pq_definir_atualizado_em()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists pq_projetos_atualizado_em on public.pq_projetos;
create trigger pq_projetos_atualizado_em
before update on public.pq_projetos
for each row execute function public.pq_definir_atualizado_em();

drop trigger if exists pq_tarefas_atualizado_em on public.pq_tarefas;
create trigger pq_tarefas_atualizado_em
before update on public.pq_tarefas
for each row execute function public.pq_definir_atualizado_em();

-- A gravacao ocorre somente pela Edge Function com permissao administrativa.
alter table public.pq_importacoes enable row level security;
alter table public.pq_projetos enable row level security;
alter table public.pq_tarefas enable row level security;
alter table public.pq_importacao_linhas enable row level security;
alter table public.pq_projetos_snapshots enable row level security;

comment on table public.pq_importacoes is
  'Historico e auditoria das planilhas importadas.';
comment on table public.pq_projetos is
  'Estado atual dos projetos recebidos do Ajure.';
comment on table public.pq_tarefas is
  'Estado atual das tarefas e Action Plans recebidos do Ajure.';
comment on table public.pq_importacao_linhas is
  'Linhas brutas recebidas em cada importacao, inclusive erros.';
comment on table public.pq_projetos_snapshots is
  'Fotografia historica dos projetos em cada importacao.';

-- Resultado final esperado: cinco linhas, todas com existe = true.
select
  nome_tabela,
  to_regclass('public.' || nome_tabela) is not null as existe
from unnest(array[
  'pq_importacoes',
  'pq_projetos',
  'pq_tarefas',
  'pq_importacao_linhas',
  'pq_projetos_snapshots'
]) as verificacao(nome_tabela)
order by nome_tabela;
