-- ============================================================
-- PROJETOS DA QUALIDADE | EDITOR E RELATÓRIO | V25.39
-- Execute este arquivo inteiro no Supabase > SQL Editor.
-- Pode ser executado novamente sem apagar versões já registradas.
-- ============================================================

create table if not exists public.pq_projetos_edicoes (
  id bigint generated by default as identity primary key,
  projeto_id bigint not null,
  versao integer not null,
  status_edicao text not null default 'rascunho',
  contexto_objetivo text,
  resultados_esperados text,
  acoes_complementares text,
  resultados_alcancados text,
  impacto text,
  observacoes text,
  evidencias jsonb not null default '[]'::jsonb,
  dados_origem jsonb not null default '{}'::jsonb,
  criado_por uuid,
  criado_por_email text,
  criado_em timestamptz not null default now()
);

alter table public.pq_projetos_edicoes
  add column if not exists projeto_id bigint,
  add column if not exists versao integer,
  add column if not exists status_edicao text default 'rascunho',
  add column if not exists contexto_objetivo text,
  add column if not exists resultados_esperados text,
  add column if not exists acoes_complementares text,
  add column if not exists resultados_alcancados text,
  add column if not exists impacto text,
  add column if not exists observacoes text,
  add column if not exists evidencias jsonb default '[]'::jsonb,
  add column if not exists dados_origem jsonb default '{}'::jsonb,
  add column if not exists criado_por uuid,
  add column if not exists criado_por_email text,
  add column if not exists criado_em timestamptz default now();

create unique index if not exists uq_pq_edicao_versao
  on public.pq_projetos_edicoes (projeto_id, versao);

alter table public.pq_projetos_edicoes enable row level security;

drop policy if exists "pq edicoes leitura" on public.pq_projetos_edicoes;
create policy "pq edicoes leitura"
  on public.pq_projetos_edicoes
  for select
  to authenticated
  using (
    lower(coalesce(auth.jwt() ->> 'email', '')) like '%@animaeducacao.com.br'
  );

grant select on public.pq_projetos_edicoes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.pq_salvar_edicao(
  p_projeto_id bigint,
  p_contexto_objetivo text,
  p_resultados_esperados text,
  p_acoes_complementares text,
  p_resultados_alcancados text,
  p_impacto text,
  p_observacoes text,
  p_evidencias jsonb,
  p_finalizar boolean default false
)
returns public.pq_projetos_edicoes
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_versao integer;
  v_origem jsonb;
  v_reg public.pq_projetos_edicoes;
begin
  if v_user is null then
    raise exception 'Usuário não autenticado.';
  end if;

  if v_email not like '%@animaeducacao.com.br' then
    raise exception 'Domínio institucional não autorizado.';
  end if;

  if not exists (
    select 1
    from public.pq_projetos_atual
    where id = p_projeto_id
      and ativo = true
  ) then
    raise exception 'Projeto não encontrado na base atual.';
  end if;

  perform pg_advisory_xact_lock(p_projeto_id);

  select coalesce(max(versao), 0) + 1
    into v_versao
    from public.pq_projetos_edicoes
    where projeto_id = p_projeto_id;

  select jsonb_build_object(
    'projeto', to_jsonb(p),
    'tarefas', coalesce((
      select jsonb_agg(to_jsonb(t) order by t.data_inicio nulls last, t.id)
      from public.vw_pq_tarefas_v245 t
      where t.projeto_id = p.id
    ), '[]'::jsonb)
  )
    into v_origem
    from public.vw_pq_projetos_v245 p
    where p.id = p_projeto_id;

  insert into public.pq_projetos_edicoes (
    projeto_id,
    versao,
    status_edicao,
    contexto_objetivo,
    resultados_esperados,
    acoes_complementares,
    resultados_alcancados,
    impacto,
    observacoes,
    evidencias,
    dados_origem,
    criado_por,
    criado_por_email
  )
  values (
    p_projeto_id,
    v_versao,
    case when p_finalizar then 'finalizada' else 'rascunho' end,
    p_contexto_objetivo,
    p_resultados_esperados,
    p_acoes_complementares,
    p_resultados_alcancados,
    p_impacto,
    p_observacoes,
    coalesce(p_evidencias, '[]'::jsonb),
    coalesce(v_origem, '{}'::jsonb),
    v_user,
    v_email
  )
  returning * into v_reg;

  return v_reg;
end;
$$;

revoke all on function public.pq_salvar_edicao(
  bigint,text,text,text,text,text,text,jsonb,boolean
) from public;

grant execute on function public.pq_salvar_edicao(
  bigint,text,text,text,text,text,text,jsonb,boolean
) to authenticated;

select
  to_regclass('public.pq_projetos_edicoes') as tabela_editor,
  to_regprocedure(
    'public.pq_salvar_edicao(bigint,text,text,text,text,text,text,jsonb,boolean)'
  ) as funcao_salvar,
  (select count(*) from public.pq_projetos_edicoes) as versoes_existentes;
