create table if not exists public.certificados_envios (
  id bigint generated by default as identity primary key,
  chave_certificado text not null,
  revisor text not null,
  email text not null,
  name_ua text,
  titulo text,
  semestre_oferta text,
  status text not null default 'enviado',
  resend_id text,
  enviado_por uuid default auth.uid(),
  enviado_em timestamptz not null default now()
);
create unique index if not exists certificados_envios_chave_enviado_uq
on public.certificados_envios(chave_certificado) where status='enviado';
alter table public.certificados_envios enable row level security;
drop policy if exists "certificados_select_institucional" on public.certificados_envios;
create policy "certificados_select_institucional" on public.certificados_envios for select to authenticated using (true);
drop policy if exists "certificados_insert_institucional" on public.certificados_envios;
create policy "certificados_insert_institucional" on public.certificados_envios for insert to authenticated with check (auth.uid() = enviado_por);
notify pgrst, 'reload schema';
