-- ============================================================
-- V25.46.40 | PROJETO QUALIDADE | TRATAMENTO DE TAREFAS NO RELEASE
-- Execute UMA VEZ no Supabase > SQL Editor.
-- Não altera versões existentes nem substitui a função pq_salvar_edicao.
-- ============================================================

alter table public.pq_projetos_edicoes
  add column if not exists tarefas_release jsonb not null default '[]'::jsonb,
  add column if not exists tarefas_release_registradas_em timestamptz;

comment on column public.pq_projetos_edicoes.tarefas_release is
  'Fotografia imutável das decisões de status das tarefas no release desta versão.';

create table if not exists public.pq_tarefas_status_auditoria (
  id bigint generated by default as identity primary key,
  tarefa_id bigint not null,
  projeto_id bigint not null,
  edicao_id bigint not null,
  status_anterior text,
  status_novo text not null,
  alterado_por uuid,
  alterado_por_email text,
  alterado_em timestamptz not null default now()
);

create index if not exists idx_pq_tarefas_status_auditoria_tarefa
  on public.pq_tarefas_status_auditoria (tarefa_id, alterado_em desc);

create index if not exists idx_pq_tarefas_status_auditoria_edicao
  on public.pq_tarefas_status_auditoria (edicao_id);

alter table public.pq_tarefas_status_auditoria enable row level security;

drop policy if exists "pq tarefas auditoria leitura" on public.pq_tarefas_status_auditoria;
create policy "pq tarefas auditoria leitura"
  on public.pq_tarefas_status_auditoria
  for select
  to authenticated
  using (
    lower(coalesce(auth.jwt() ->> 'email', '')) like '%@animaeducacao.com.br'
  );

grant select on public.pq_tarefas_status_auditoria to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Check leve usado pelo front-end antes de criar uma versão.
create or replace function public.pq_release_tarefas_disponivel()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'ok', true,
    'versao', '25.46.40'
  );
$$;

revoke all on function public.pq_release_tarefas_disponivel() from public;
grant execute on function public.pq_release_tarefas_disponivel() to authenticated;

-- Grava a fotografia das decisões de tarefas uma única vez na versão recém-criada.
create or replace function public.pq_salvar_tarefas_release(
  p_edicao_id bigint,
  p_tarefas jsonb
)
returns public.pq_projetos_edicoes
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_reg public.pq_projetos_edicoes;
begin
  if v_user is null then
    raise exception 'Usuário não autenticado.';
  end if;

  if v_email not like '%@animaeducacao.com.br' then
    raise exception 'Domínio institucional não autorizado.';
  end if;

  update public.pq_projetos_edicoes
     set tarefas_release = coalesce(p_tarefas, '[]'::jsonb),
         tarefas_release_registradas_em = now()
   where id = p_edicao_id
     and criado_por = v_user
     and criado_em >= now() - interval '10 minutes'
     and tarefas_release_registradas_em is null
  returning * into v_reg;

  if v_reg.id is null then
    raise exception 'Tratamento de tarefas não gravado: versão inexistente, antiga, de outro usuário ou já protegida.';
  end if;

  return v_reg;
end;
$$;

revoke all on function public.pq_salvar_tarefas_release(bigint,jsonb) from public;
grant execute on function public.pq_salvar_tarefas_release(bigint,jsonb) to authenticated;

-- Atualiza explicitamente o status atual da tarefa somente quando a pessoa
-- escolheu "Finalizar e atualizar também o Projeto Qualidade" e a versão já
-- foi finalizada. O histórico original do release permanece preservado.
create or replace function public.pq_aplicar_status_tarefa(
  p_tarefa_id bigint,
  p_edicao_id bigint,
  p_status_novo text default 'Finalizado'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_edicao public.pq_projetos_edicoes;
  v_tarefa_id bigint;
  v_projeto_id bigint;
  v_status_anterior text;
  v_status_novo text := nullif(trim(coalesce(p_status_novo, '')), '');
begin
  if v_user is null then
    raise exception 'Usuário não autenticado.';
  end if;

  if v_email not like '%@animaeducacao.com.br' then
    raise exception 'Domínio institucional não autorizado.';
  end if;

  if v_status_novo is null then
    v_status_novo := 'Finalizado';
  end if;

  select *
    into v_edicao
    from public.pq_projetos_edicoes
   where id = p_edicao_id
     and criado_por = v_user
     and status_edicao = 'finalizada'
     and criado_em >= now() - interval '10 minutes';

  if v_edicao.id is null then
    raise exception 'Versão finalizada não localizada ou fora da janela segura de atualização.';
  end if;

  select id, projeto_id, status
    into v_tarefa_id, v_projeto_id, v_status_anterior
    from public.pq_tarefas_atual
   where id = p_tarefa_id
     and ativo = true
   for update;

  if v_tarefa_id is null then
    raise exception 'Tarefa ativa não localizada.';
  end if;

  if v_projeto_id is distinct from v_edicao.projeto_id then
    raise exception 'A tarefa não pertence ao projeto desta versão.';
  end if;

  if lower(trim(coalesce(v_status_anterior, ''))) = lower(trim(v_status_novo)) then
    return jsonb_build_object(
      'ok', true,
      'alterada', false,
      'tarefa_id', p_tarefa_id,
      'status_anterior', v_status_anterior,
      'status_novo', v_status_novo
    );
  end if;

  update public.pq_tarefas_atual
     set status = v_status_novo,
         updated_at = now()
   where id = p_tarefa_id
     and ativo = true;

  insert into public.pq_tarefas_status_auditoria (
    tarefa_id,
    projeto_id,
    edicao_id,
    status_anterior,
    status_novo,
    alterado_por,
    alterado_por_email
  ) values (
    p_tarefa_id,
    v_edicao.projeto_id,
    p_edicao_id,
    v_status_anterior,
    v_status_novo,
    v_user,
    v_email
  );

  return jsonb_build_object(
    'ok', true,
    'alterada', true,
    'tarefa_id', p_tarefa_id,
    'status_anterior', v_status_anterior,
    'status_novo', v_status_novo
  );
end;
$$;

revoke all on function public.pq_aplicar_status_tarefa(bigint,bigint,text) from public;
grant execute on function public.pq_aplicar_status_tarefa(bigint,bigint,text) to authenticated;

select
  exists (
    select 1
      from information_schema.columns
     where table_schema = 'public'
       and table_name = 'pq_projetos_edicoes'
       and column_name = 'tarefas_release'
  ) as coluna_tarefas_release,
  to_regprocedure('public.pq_release_tarefas_disponivel()') as funcao_check,
  to_regprocedure('public.pq_salvar_tarefas_release(bigint,jsonb)') as funcao_snapshot,
  to_regprocedure('public.pq_aplicar_status_tarefa(bigint,bigint,text)') as funcao_atualizar_status;
