-- ============================================================
-- V25.46.41 — Correção auditada de revisor de certificados
-- Mantém histórico sem alterar a Monday.
-- ============================================================

create table if not exists public.certificados_revisor_ajustes (
  id bigint generated by default as identity primary key,
  monday_item_id text not null,
  revisor_chave text not null,
  revisor_monday_id text,
  revisor_original text,
  email_original text,
  revisor_corrigido text not null,
  email_corrigido text,
  motivo text not null,
  ativo boolean not null default true,
  criado_por uuid default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_por uuid,
  atualizado_em timestamptz not null default now()
);

create index if not exists certificados_revisor_ajustes_item_idx
  on public.certificados_revisor_ajustes (monday_item_id);

create index if not exists certificados_revisor_ajustes_revisor_idx
  on public.certificados_revisor_ajustes (revisor_chave);

-- Garante apenas um ajuste vigente por item + revisor original,
-- sem apagar os ajustes históricos já desativados.
create unique index if not exists certificados_revisor_ajustes_ativo_uidx
  on public.certificados_revisor_ajustes (monday_item_id, revisor_chave)
  where ativo = true;

alter table public.certificados_revisor_ajustes enable row level security;

-- Políticas idempotentes
drop policy if exists certificados_revisor_ajustes_select
  on public.certificados_revisor_ajustes;
drop policy if exists certificados_revisor_ajustes_insert
  on public.certificados_revisor_ajustes;
drop policy if exists certificados_revisor_ajustes_update
  on public.certificados_revisor_ajustes;

create policy certificados_revisor_ajustes_select
  on public.certificados_revisor_ajustes
  for select
  to authenticated
  using (true);

create policy certificados_revisor_ajustes_insert
  on public.certificados_revisor_ajustes
  for insert
  to authenticated
  with check (true);

create policy certificados_revisor_ajustes_update
  on public.certificados_revisor_ajustes
  for update
  to authenticated
  using (true)
  with check (true);

create or replace function public.certificados_revisor_ajustes_set_atualizacao()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.atualizado_em = now();
  new.atualizado_por = auth.uid();
  return new;
end;
$$;

drop trigger if exists trg_certificados_revisor_ajustes_atualizacao
  on public.certificados_revisor_ajustes;

create trigger trg_certificados_revisor_ajustes_atualizacao
before update on public.certificados_revisor_ajustes
for each row
execute function public.certificados_revisor_ajustes_set_atualizacao();

-- Conferência final
select
  to_regclass('public.certificados_revisor_ajustes') is not null as tabela_criada,
  exists (
    select 1
    from pg_indexes
    where schemaname = 'public'
      and tablename = 'certificados_revisor_ajustes'
      and indexname = 'certificados_revisor_ajustes_ativo_uidx'
  ) as historico_ativo_controlado;
