-- V25.46.52 | Planejamento integrado ao BI
-- Execute este arquivo inteiro no SQL Editor do mesmo Supabase do BI.
-- Instalação aditiva e reaplicável. Não modifica as tabelas existentes.
begin;

create table if not exists public.bi_planejamento_tarefas (
  id uuid primary key default gen_random_uuid(),
  titulo text not null check (length(trim(titulo)) between 1 and 200),
  descricao text not null default '' check (length(descricao) <= 12000),
  responsavel text not null default '' check (length(responsavel) <= 300),
  prazo date,
  status text not null default 'a_fazer' check (status in ('a_fazer','em_andamento','bloqueada','concluida')),
  prioridade text not null default 'media' check (prioridade in ('baixa','media','alta','critica')),
  atencao boolean not null default false,
  etapas jsonb not null default '[]'::jsonb check (jsonb_typeof(etapas) = 'array' and jsonb_array_length(etapas) <= 100),
  vinculos jsonb not null default '[]'::jsonb check (jsonb_typeof(vinculos) = 'array' and jsonb_array_length(vinculos) <= 40),
  arquivada boolean not null default false,
  versao bigint not null default 1,
  criado_por uuid not null,
  criado_por_email text not null,
  atualizado_por uuid not null,
  atualizado_por_email text not null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
create index if not exists bi_planejamento_status_prazo on public.bi_planejamento_tarefas (arquivada,status,prazo);
create index if not exists bi_planejamento_vinculos on public.bi_planejamento_tarefas using gin (vinculos);

create table if not exists public.bi_planejamento_historico (
  id bigint generated by default as identity primary key,
  tarefa_id uuid not null references public.bi_planejamento_tarefas(id),
  acao text not null check (acao in ('criada','alterada','arquivada','restaurada','comentario')),
  comentario text,
  antes jsonb,
  depois jsonb,
  usuario_id uuid not null,
  usuario_email text not null,
  criado_em timestamptz not null default now()
);
create index if not exists bi_planejamento_historico_tarefa on public.bi_planejamento_historico(tarefa_id,criado_em desc,id desc);

create or replace function public.bi_planejamento_permitido()
returns boolean language sql stable security invoker set search_path = '' as $$
  select auth.uid() is not null
     and lower(split_part(coalesce(auth.jwt()->>'email',''),'@',2)) = 'animaeducacao.com.br';
$$;
revoke all on function public.bi_planejamento_permitido() from public, anon;
grant execute on function public.bi_planejamento_permitido() to authenticated;

alter table public.bi_planejamento_tarefas enable row level security;
alter table public.bi_planejamento_historico enable row level security;
drop policy if exists bi_planejamento_leitura on public.bi_planejamento_tarefas;
create policy bi_planejamento_leitura on public.bi_planejamento_tarefas for select to authenticated using (public.bi_planejamento_permitido());
drop policy if exists bi_planejamento_historico_leitura on public.bi_planejamento_historico;
create policy bi_planejamento_historico_leitura on public.bi_planejamento_historico for select to authenticated using (public.bi_planejamento_permitido());
revoke all on public.bi_planejamento_tarefas, public.bi_planejamento_historico from anon, authenticated;
grant select on public.bi_planejamento_tarefas, public.bi_planejamento_historico to authenticated;

create or replace function public.bi_planejamento_salvar(p_id uuid, p_versao bigint, p_dados jsonb)
returns public.bi_planejamento_tarefas
language plpgsql security definer set search_path = '' as $$
declare
  v_antigo public.bi_planejamento_tarefas;
  v_novo public.bi_planejamento_tarefas;
  v_etapas jsonb := coalesce(p_dados->'etapas','[]'::jsonb);
  v_vinculos jsonb := coalesce(p_dados->'vinculos','[]'::jsonb);
  v_item jsonb;
  v_email text := lower(coalesce(auth.jwt()->>'email',''));
  v_acao text;
begin
  if not public.bi_planejamento_permitido() then raise exception 'Sessão institucional não autorizada.'; end if;
  if jsonb_typeof(p_dados) is distinct from 'object' then raise exception 'Dados da tarefa inválidos.'; end if;
  if jsonb_typeof(v_etapas) is distinct from 'array' or jsonb_typeof(v_vinculos) is distinct from 'array' then
    raise exception 'Etapas e vínculos devem ser listas.';
  end if;
  if jsonb_array_length(v_etapas) > 100 or jsonb_array_length(v_vinculos) > 40 or octet_length(p_dados::text) > 250000 then
    raise exception 'Limite de etapas ou vínculos excedido.';
  end if;
  for v_item in select value from jsonb_array_elements(v_etapas) loop
    if jsonb_typeof(v_item) is distinct from 'object'
      or coalesce(length(trim(v_item->>'id')),0) not between 1 and 100
      or coalesce(length(trim(v_item->>'titulo')),0) not between 1 and 300
      or jsonb_typeof(v_item->'concluida') is distinct from 'boolean'
      or length(coalesce(v_item->>'responsavel','')) > 300 then
      raise exception 'Etapa inválida: informe título, identificador e conclusão.';
    end if;
    perform nullif(v_item->>'prazo','')::date;
  end loop;
  if (select count(*) from jsonb_array_elements(v_etapas)) <>
     (select count(distinct value->>'id') from jsonb_array_elements(v_etapas)) then
    raise exception 'Há etapas com identificadores repetidos.';
  end if;
  for v_item in select value from jsonb_array_elements(v_vinculos) loop
    if jsonb_typeof(v_item) is distinct from 'object'
      or coalesce(length(v_item->>'id'),0) not between 1 and 500
      or coalesce(length(v_item->>'label'),0) not between 1 and 600
      or coalesce(v_item->>'tipo','') not in ('visao','material','projeto','tarefa_projeto','professor','revisor','certificado')
      or jsonb_typeof(v_item->'dados') is distinct from 'object'
      or coalesce(v_item->>'pagina','') not in ('resumo','resultados','reuniao-nq','indicadores-uc','gestores-materiais','certificados','projeto-qualidade','operacao','ajustes','equipe','grafico-operacional','dias-validacao','historico') then
      raise exception 'Vínculo com o BI inválido.';
    end if;
  end loop;
  if p_dados->>'status' = 'concluida' and exists (
    select 1 from jsonb_array_elements(v_etapas) where not (value->>'concluida')::boolean
  ) then raise exception 'Conclua os passos antes de concluir a tarefa.'; end if;

  if p_id is not null then
    select * into v_antigo from public.bi_planejamento_tarefas where id=p_id for update;
    if not found then raise exception 'Tarefa não localizada.'; end if;
    if p_versao is distinct from v_antigo.versao then
      raise exception 'Outra pessoa alterou esta tarefa. Atualize a lista e reabra a tarefa antes de salvar.';
    end if;
    update public.bi_planejamento_tarefas set
      titulo=trim(p_dados->>'titulo'), descricao=coalesce(p_dados->>'descricao',''),
      responsavel=trim(coalesce(p_dados->>'responsavel','')), prazo=nullif(p_dados->>'prazo','')::date,
      status=coalesce(p_dados->>'status','a_fazer'), prioridade=coalesce(p_dados->>'prioridade','media'),
      atencao=coalesce((p_dados->>'atencao')::boolean,false), etapas=v_etapas, vinculos=v_vinculos,
      arquivada=coalesce((p_dados->>'arquivada')::boolean,false), versao=versao+1,
      atualizado_por=auth.uid(), atualizado_por_email=v_email, atualizado_em=now()
    where id=p_id returning * into v_novo;
    v_acao := case when v_novo.arquivada and not v_antigo.arquivada then 'arquivada'
                   when not v_novo.arquivada and v_antigo.arquivada then 'restaurada' else 'alterada' end;
  else
    insert into public.bi_planejamento_tarefas (
      titulo,descricao,responsavel,prazo,status,prioridade,atencao,etapas,vinculos,
      criado_por,criado_por_email,atualizado_por,atualizado_por_email
    ) values (
      trim(p_dados->>'titulo'),coalesce(p_dados->>'descricao',''),trim(coalesce(p_dados->>'responsavel','')),
      nullif(p_dados->>'prazo','')::date,coalesce(p_dados->>'status','a_fazer'),coalesce(p_dados->>'prioridade','media'),
      coalesce((p_dados->>'atencao')::boolean,false),v_etapas,v_vinculos,auth.uid(),v_email,auth.uid(),v_email
    ) returning * into v_novo;
    v_acao := 'criada';
  end if;
  insert into public.bi_planejamento_historico(tarefa_id,acao,antes,depois,usuario_id,usuario_email)
  values(v_novo.id,v_acao,case when p_id is null then null else to_jsonb(v_antigo) end,to_jsonb(v_novo),auth.uid(),v_email);
  return v_novo;
end;
$$;
revoke all on function public.bi_planejamento_salvar(uuid,bigint,jsonb) from public,anon;
grant execute on function public.bi_planejamento_salvar(uuid,bigint,jsonb) to authenticated;

create or replace function public.bi_planejamento_comentar(p_tarefa_id uuid,p_comentario text)
returns public.bi_planejamento_historico
language plpgsql security definer set search_path = '' as $$
declare v_reg public.bi_planejamento_historico;
begin
  if not public.bi_planejamento_permitido() then raise exception 'Sessão institucional não autorizada.'; end if;
  if coalesce(length(trim(p_comentario)),0) not between 1 and 4000 then raise exception 'Informe um comentário com até 4.000 caracteres.'; end if;
  if not exists(select 1 from public.bi_planejamento_tarefas where id=p_tarefa_id) then raise exception 'Tarefa não localizada.'; end if;
  insert into public.bi_planejamento_historico(tarefa_id,acao,comentario,usuario_id,usuario_email)
  values(p_tarefa_id,'comentario',trim(p_comentario),auth.uid(),lower(auth.jwt()->>'email')) returning * into v_reg;
  return v_reg;
end;
$$;
revoke all on function public.bi_planejamento_comentar(uuid,text) from public,anon;
grant execute on function public.bi_planejamento_comentar(uuid,text) to authenticated;

notify pgrst,'reload schema';
commit;
select 'Planejamento V25.46.52 instalado' as resultado;
