-- V21.1 — preparar histórico e agendamento da sincronização dos Indicadores da UC
-- Execute TODO este arquivo no SQL Editor do Supabase.

create table if not exists public.sync_log (
  id bigint generated by default as identity primary key,
  rotina text not null default 'sync-criterios-avaliacao-uas',
  status text not null default 'sucesso',
  itens_lidos integer,
  itens_gravados integer,
  erros integer default 0,
  mensagem text,
  created_at timestamptz not null default now()
);

alter table public.sync_log enable row level security;

drop policy if exists "sync_log leitura autenticados" on public.sync_log;
create policy "sync_log leitura autenticados"
on public.sync_log for select
to authenticated
using (true);

-- Extensões necessárias para chamada HTTP agendada.
create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;

-- Remove agendamento anterior com o mesmo nome, caso exista.
do $$
declare jid bigint;
begin
  select jobid into jid from cron.job where jobname = 'sync-criterios-uc-3x-dia' limit 1;
  if jid is not null then perform cron.unschedule(jid); end if;
end $$;

-- 08:00, 13:00 e 18:00 de Brasília = 11:00, 16:00 e 21:00 UTC.
select cron.schedule(
  'sync-criterios-uc-3x-dia',
  '0 11,16,21 * * *',
  $cron$
  select net.http_post(
    url := 'https://nkjmgzyjjbepebzurowy.supabase.co/functions/v1/sync-criterios-avaliacao-uas',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer sb_publishable_6Tuuyz6nYSBa782OGDi1rg_XkBHmO8U'
    ),
    body := '{}'::jsonb
  );
  $cron$
);

-- Conferência do agendamento:
select jobid, jobname, schedule, active
from cron.job
where jobname = 'sync-criterios-uc-3x-dia';
