-- ============================================================
-- BI MONDAY V23.7
-- Projeto Qualidade | Base atual isolada do legado
-- Execute este BLOCO INTEIRO no SQL Editor do Supabase.
-- ============================================================

-- 1. Projetos atuais
CREATE TABLE IF NOT EXISTS public.pq_projetos_atual (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key text NOT NULL,
    id_azure text,
    projeto text NOT NULL,
    status text,
    data_inicio date,
    data_fim date,
    sponsor text,
    esforco text,
    prioridade text,
    link_evidencias text,
    ativo boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_pq_projetos_atual_source_key UNIQUE (source_key)
);

-- 2. Tarefas atuais
CREATE TABLE IF NOT EXISTS public.pq_tarefas_atual (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key text NOT NULL,
    id_azure text,
    projeto text NOT NULL,
    acao text,
    status text,
    data_inicio date,
    data_fim date,
    sponsor text,
    link_evidencias text,
    ativo boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_pq_tarefas_atual_source_key UNIQUE (source_key)
);

CREATE INDEX IF NOT EXISTS idx_pq_projetos_atual_projeto
ON public.pq_projetos_atual (projeto);

CREATE INDEX IF NOT EXISTS idx_pq_projetos_atual_sponsor
ON public.pq_projetos_atual (sponsor);

CREATE INDEX IF NOT EXISTS idx_pq_tarefas_atual_projeto
ON public.pq_tarefas_atual (projeto);

-- 3. Segurança
ALTER TABLE public.pq_projetos_atual ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pq_tarefas_atual ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pq projetos atual leitura" ON public.pq_projetos_atual;
CREATE POLICY "pq projetos atual leitura"
ON public.pq_projetos_atual
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "pq tarefas atual leitura" ON public.pq_tarefas_atual;
CREATE POLICY "pq tarefas atual leitura"
ON public.pq_tarefas_atual
FOR SELECT
TO authenticated
USING (true);

GRANT SELECT ON public.pq_projetos_atual TO authenticated;
GRANT SELECT ON public.pq_tarefas_atual TO authenticated;

-- 4. Garantir histórico de importação
ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS arquivo_nome text;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS arquivo_tamanho bigint;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS aba text;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS status text;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS total_linhas integer DEFAULT 0;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS projetos_inseridos integer DEFAULT 0;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS projetos_atualizados integer DEFAULT 0;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS tarefas_inseridas integer DEFAULT 0;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS tarefas_atualizadas integer DEFAULT 0;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS linhas_com_erro integer DEFAULT 0;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS mensagem text;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS importado_por uuid;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS finished_at timestamptz;

ALTER TABLE public.pq_importacoes
ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

ALTER TABLE public.pq_importacoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pq importacoes leitura" ON public.pq_importacoes;
CREATE POLICY "pq importacoes leitura"
ON public.pq_importacoes
FOR SELECT
TO authenticated
USING (true);

GRANT SELECT ON public.pq_importacoes TO authenticated;

-- 5. Conferência inicial
SELECT
    'pq_projetos_atual' AS tabela,
    COUNT(*) AS registros
FROM public.pq_projetos_atual

UNION ALL

SELECT
    'pq_tarefas_atual',
    COUNT(*)
FROM public.pq_tarefas_atual;
