-- ============================================================
-- BI MONDAY V23
-- NQ | Importação recorrente da planilha de especialistas
-- Execute o BLOCO INTEIRO no SQL Editor do Supabase.
-- ============================================================

-- 1. Histórico das importações
CREATE TABLE IF NOT EXISTS public.nq_importacoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arquivo_nome text NOT NULL,
    arquivo_tamanho bigint,
    aba text NOT NULL DEFAULT 'Export',
    status text NOT NULL DEFAULT 'processando',
    total_linhas integer DEFAULT 0,
    especialistas_gravados integer DEFAULT 0,
    especialistas_novos integer DEFAULT 0,
    especialistas_atualizados integer DEFAULT 0,
    especialistas_inativados integer DEFAULT 0,
    formacoes_gravadas integer DEFAULT 0,
    linhas_com_erro integer DEFAULT 0,
    mensagem text,
    importado_por uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_nq_importacoes_created_at
ON public.nq_importacoes (created_at DESC);

ALTER TABLE public.nq_importacoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "nq importacoes leitura" ON public.nq_importacoes;
CREATE POLICY "nq importacoes leitura"
ON public.nq_importacoes
FOR SELECT
TO authenticated
USING (true);

GRANT SELECT ON public.nq_importacoes TO authenticated;


-- 2. CPF normalizado para identificar a mesma pessoa entre importações.
ALTER TABLE public.nq_especialistas
ADD COLUMN IF NOT EXISTS cpf_normalizado text;

CREATE UNIQUE INDEX IF NOT EXISTS uq_nq_especialistas_cpf_normalizado
ON public.nq_especialistas (cpf_normalizado)
WHERE cpf_normalizado IS NOT NULL
  AND cpf_normalizado <> '';


-- 3. Segurança: o frontend não precisa consultar CPF/telefone diretamente.
-- As views do relatório continuam disponíveis.
REVOKE SELECT ON public.nq_especialistas FROM authenticated;

GRANT SELECT ON public.vw_nq_especialistas_formacoes TO authenticated;
GRANT SELECT ON public.vw_nq_cobertura_especialistas TO authenticated;
GRANT SELECT ON public.nq_especialistas_formacoes TO authenticated;
GRANT SELECT ON public.nq_especialistas_experiencias TO authenticated;
GRANT SELECT ON public.nq_areas_cine TO authenticated;


-- 4. View para histórico resumido da importação
CREATE OR REPLACE VIEW public.vw_nq_importacoes_resumo AS
SELECT
    id,
    arquivo_nome,
    status,
    total_linhas,
    especialistas_gravados,
    especialistas_novos,
    especialistas_atualizados,
    especialistas_inativados,
    formacoes_gravadas,
    linhas_com_erro,
    mensagem,
    created_at,
    finished_at
FROM public.nq_importacoes
ORDER BY created_at DESC;

GRANT SELECT ON public.vw_nq_importacoes_resumo TO authenticated;


-- 5. Teste
SELECT
    table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name = 'nq_importacoes';
