-- ============================================================
-- BI MONDAY V23.8
-- Projeto Qualidade | Base atual completamente isolada
-- Execute este BLOCO INTEIRO no SQL Editor.
-- ============================================================

-- 1. Garantir tabelas atuais de projetos e tarefas
CREATE TABLE IF NOT EXISTS public.pq_projetos_atual (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key text NOT NULL,
    id_azure text,
    projeto text NOT NULL,
    status text,
    data_inicio date,
    data_fim date,
    sponsor text,
    esforco text,
    prioridade text,
    link_evidencias text,
    ativo boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_pq_projetos_atual_source_key UNIQUE (source_key)
);

CREATE TABLE IF NOT EXISTS public.pq_tarefas_atual (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key text NOT NULL,
    id_azure text,
    projeto text NOT NULL,
    acao text,
    status text,
    data_inicio date,
    data_fim date,
    sponsor text,
    link_evidencias text,
    ativo boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_pq_tarefas_atual_source_key UNIQUE (source_key)
);

-- 2. NOVA tabela de histórico, sem dependência do schema antigo
CREATE TABLE IF NOT EXISTS public.pq_importacoes_atual (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arquivo_nome text NOT NULL,
    arquivo_tamanho bigint,
    aba text,
    status text NOT NULL DEFAULT 'processando',
    total_linhas integer NOT NULL DEFAULT 0,
    projetos_inseridos integer NOT NULL DEFAULT 0,
    projetos_atualizados integer NOT NULL DEFAULT 0,
    tarefas_inseridas integer NOT NULL DEFAULT 0,
    tarefas_atualizadas integer NOT NULL DEFAULT 0,
    linhas_com_erro integer NOT NULL DEFAULT 0,
    mensagem text,
    importado_por uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_pq_projetos_atual_projeto
ON public.pq_projetos_atual (projeto);

CREATE INDEX IF NOT EXISTS idx_pq_projetos_atual_sponsor
ON public.pq_projetos_atual (sponsor);

CREATE INDEX IF NOT EXISTS idx_pq_tarefas_atual_projeto
ON public.pq_tarefas_atual (projeto);

CREATE INDEX IF NOT EXISTS idx_pq_importacoes_atual_created
ON public.pq_importacoes_atual (created_at DESC);

-- 3. RLS + leitura pelo BI
ALTER TABLE public.pq_projetos_atual ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pq_tarefas_atual ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pq_importacoes_atual ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pq projetos atual leitura" ON public.pq_projetos_atual;
CREATE POLICY "pq projetos atual leitura"
ON public.pq_projetos_atual FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "pq tarefas atual leitura" ON public.pq_tarefas_atual;
CREATE POLICY "pq tarefas atual leitura"
ON public.pq_tarefas_atual FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "pq importacoes atual leitura" ON public.pq_importacoes_atual;
CREATE POLICY "pq importacoes atual leitura"
ON public.pq_importacoes_atual FOR SELECT TO authenticated USING (true);

GRANT SELECT ON public.pq_projetos_atual TO authenticated;
GRANT SELECT ON public.pq_tarefas_atual TO authenticated;
GRANT SELECT ON public.pq_importacoes_atual TO authenticated;

-- 4. Conferência
SELECT 'pq_projetos_atual' AS tabela, COUNT(*) AS registros
FROM public.pq_projetos_atual

UNION ALL

SELECT 'pq_tarefas_atual', COUNT(*)
FROM public.pq_tarefas_atual

UNION ALL

SELECT 'pq_importacoes_atual', COUNT(*)
FROM public.pq_importacoes_atual;
