-- ============================================================
-- BI MONDAY V24.5
-- Projeto Qualidade no padrão visual/funcional da pasta V24.4
-- Compatível com a base atual V23.8/V23.9.
-- EXECUTE ESTE BLOCO INTEIRO no SQL Editor do Supabase.
-- ============================================================

-- 1. Views de compatibilidade: mantêm a base atual sem duplicar dados.
CREATE OR REPLACE VIEW public.vw_pq_projetos_v245 AS
SELECT
    p.id,
    p.id_azure AS azure_id,
    p.projeto AS nome,
    p.status,
    p.data_inicio,
    p.data_fim,
    p.sponsor,
    p.esforco,
    p.prioridade,
    p.link_evidencias,
    p.ativo,
    p.created_at,
    p.updated_at
FROM public.pq_projetos_atual p
WHERE p.ativo = true;

CREATE OR REPLACE VIEW public.vw_pq_tarefas_v245 AS
SELECT
    t.id,
    t.id_azure AS azure_id,
    p.id AS projeto_id,
    t.projeto AS projeto_nome,
    t.acao AS nome,
    t.status,
    t.data_inicio,
    t.data_fim,
    t.sponsor,
    t.link_evidencias,
    t.ativo,
    t.created_at,
    t.updated_at
FROM public.pq_tarefas_atual t
LEFT JOIN public.pq_projetos_atual p
       ON lower(trim(p.projeto)) = lower(trim(t.projeto))
      AND p.ativo = true
WHERE t.ativo = true;

CREATE OR REPLACE VIEW public.vw_pq_importacoes_v245 AS
SELECT
    i.id,
    i.arquivo_nome,
    i.status,
    i.total_linhas,
    i.linhas_com_erro,
    i.created_at,
    i.finished_at AS finalizado_em
FROM public.pq_importacoes_atual i;

GRANT SELECT ON public.vw_pq_projetos_v245 TO authenticated;
GRANT SELECT ON public.vw_pq_tarefas_v245 TO authenticated;
GRANT SELECT ON public.vw_pq_importacoes_v245 TO authenticated;

-- 2. Histórico de versões do relatório.
CREATE TABLE IF NOT EXISTS public.pq_projetos_edicoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id bigint NOT NULL,
    versao integer NOT NULL,
    status_edicao text NOT NULL DEFAULT 'rascunho',
    contexto_objetivo text,
    resultados_esperados text,
    acoes_complementares text,
    resultados_alcancados text,
    impacto text,
    observacoes text,
    evidencias jsonb NOT NULL DEFAULT '[]'::jsonb,
    dados_origem jsonb NOT NULL DEFAULT '{}'::jsonb,
    criado_por uuid,
    criado_por_email text,
    criado_em timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_pq_edicao_versao UNIQUE (projeto_id, versao)
);

ALTER TABLE public.pq_projetos_edicoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pq edicoes leitura" ON public.pq_projetos_edicoes;
CREATE POLICY "pq edicoes leitura"
ON public.pq_projetos_edicoes
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "pq edicoes insercao" ON public.pq_projetos_edicoes;
CREATE POLICY "pq edicoes insercao"
ON public.pq_projetos_edicoes
FOR INSERT TO authenticated
WITH CHECK (auth.uid() = criado_por);

GRANT SELECT, INSERT ON public.pq_projetos_edicoes TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.pq_projetos_edicoes_id_seq TO authenticated;

-- 3. Função: cada salvamento cria uma nova versão e fotografa a origem.
CREATE OR REPLACE FUNCTION public.pq_salvar_edicao(
    p_projeto_id bigint,
    p_contexto_objetivo text,
    p_resultados_esperados text,
    p_acoes_complementares text,
    p_resultados_alcancados text,
    p_impacto text,
    p_observacoes text,
    p_evidencias jsonb,
    p_finalizar boolean DEFAULT false
)
RETURNS public.pq_projetos_edicoes
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_user uuid := auth.uid();
    v_email text := coalesce(auth.jwt() ->> 'email', 'usuario');
    v_versao integer;
    v_origem jsonb;
    v_reg public.pq_projetos_edicoes;
BEGIN
    IF v_user IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.pq_projetos_atual
        WHERE id = p_projeto_id AND ativo = true
    ) THEN
        RAISE EXCEPTION 'Projeto não encontrado na base atual.';
    END IF;

    SELECT coalesce(max(versao), 0) + 1
      INTO v_versao
      FROM public.pq_projetos_edicoes
     WHERE projeto_id = p_projeto_id;

    SELECT jsonb_build_object(
        'projeto', to_jsonb(p),
        'tarefas', coalesce((
            SELECT jsonb_agg(to_jsonb(t) ORDER BY t.data_inicio NULLS LAST, t.id)
            FROM public.vw_pq_tarefas_v245 t
            WHERE t.projeto_id = p.id
        ), '[]'::jsonb)
    )
    INTO v_origem
    FROM public.vw_pq_projetos_v245 p
    WHERE p.id = p_projeto_id;

    INSERT INTO public.pq_projetos_edicoes (
        projeto_id, versao, status_edicao,
        contexto_objetivo, resultados_esperados, acoes_complementares,
        resultados_alcancados, impacto, observacoes, evidencias,
        dados_origem, criado_por, criado_por_email
    )
    VALUES (
        p_projeto_id, v_versao,
        CASE WHEN p_finalizar THEN 'finalizada' ELSE 'rascunho' END,
        p_contexto_objetivo, p_resultados_esperados, p_acoes_complementares,
        p_resultados_alcancados, p_impacto, p_observacoes,
        coalesce(p_evidencias, '[]'::jsonb),
        v_origem, v_user, v_email
    )
    RETURNING * INTO v_reg;

    RETURN v_reg;
END;
$$;

REVOKE ALL ON FUNCTION public.pq_salvar_edicao(bigint,text,text,text,text,text,text,jsonb,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pq_salvar_edicao(bigint,text,text,text,text,text,text,jsonb,boolean) TO authenticated;

-- 4. Conferência.
SELECT
    (SELECT count(*) FROM public.vw_pq_projetos_v245) AS projetos_atuais,
    (SELECT count(*) FROM public.vw_pq_tarefas_v245) AS tarefas_atuais,
    (SELECT count(*) FROM public.vw_pq_importacoes_v245) AS importacoes,
    (SELECT count(*) FROM public.pq_projetos_edicoes) AS versoes_salvas;
