-- V25.16 | Carga imediata da aba Diplomas
-- Gerado a partir de 01_Profs_TIs_NQ_Curriculo_Lattes_Corrigido.xlsx
-- Esperado ao final: 127 formações, 111 concluídas, 16 em andamento e 10 Áreas CINE.

BEGIN;

WITH dados(professor, nivel, curso_titulo, situacao, area_cine) AS (
  VALUES
    ('ADRIANO RODRIGUES TEIXEIRA', 'Graduação', 'Matemática', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('ADRIANO RODRIGUES TEIXEIRA', 'Especialização', 'Matemática Pura', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('ADRIANO RODRIGUES TEIXEIRA', 'Mestrado', 'Matemática (profissional)', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('ADRIANO RODRIGUES TEIXEIRA', 'Graduação', 'Física (Licenciatura)', 'Concluído', 'Educação'),
    ('ADRIANO RODRIGUES TEIXEIRA', 'Especialização', 'Gestão de Pessoas', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Graduação', 'Psicologia', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Neuropsicologia', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Psicologia Organizacional', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Futuros Acadêmicos e Currículos Integrados', 'Em andamento', 'Educação'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Graduação', 'Direito', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Recursos Ambientais e Poluição', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Direito Militar', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Perícia Criminal e Judicial', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Direito Médico e Saúde', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Mestrado', 'Psicologia Forense', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Tecnologia em Informática e Gestão da Informação', 'Concluído', 'Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Ciência da Computação (Licenciatura)', 'Concluído', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Pedagogia', 'Concluído', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Coordenação Pedagógica para a Educação Básica', 'Concluído', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Docência do Ensino Superior', 'Concluído', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Docência e Tutoria em EAD', 'Concluído', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Sociologia Licenciatura', 'Em andamento', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Tecnologia em Saneamento Ambiental', 'Concluído', 'Engenharia, produção e construção'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Engenharia de Produção', 'Em andamento', 'Engenharia, produção e construção'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Administração', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Ciências Contábeis', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Direito', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Gestão Comercial', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Advocacia da Fazenda Pública', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Auditoria e Compliance', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Controle Interno na Administração Pública', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Administrativo com Ênfase em Carreiras de Tribunais', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Constitucional Aplicado', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Desportivo Aplicado', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito do Consumidor', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito do Trabalho e Processual do Trabalho', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Imobiliário', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Internacional', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Privado', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Público', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direitos Humanos', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Executivo em Gestão de Pessoas & Coaching', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Gestão de Cidades', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Gestão Empresarial', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Gestão Estratégica da Administração Pública', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Gestão Pública Municipal', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Planejamento Patrimonial, Familiar e Sucessório', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Planejamento Previdenciário', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Planejamento Tributário', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Advocacia Extrajudicial', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Mestrado', 'Sociedade, Tecnologias e Politicas Públicas', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Doutorado', 'Desenvolvimento e Meio Ambiente', 'Em andamento', 'Negócios, administração e direito'),
    ('CARLOS PEREIRA MARTINS', 'Mestrado', 'Neurociências', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('CARLOS PEREIRA MARTINS', 'Doutorado', 'Neurociências', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Gestão Pública na Educação Profissional e Tecnológica', 'Concluído', 'Negócios, administração e direito'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Auditoria em Serviços de Saúde', 'Em andamento', 'Negócios, administração e direito'),
    ('CARLOS PEREIRA MARTINS', 'Graduação', 'Enfermagem (Bacharelado)', 'Concluído', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Urgência e Emergência', 'Concluído', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Enfermagem na Atenção Primária com Ênfase na Estratégia Saúde da Família', 'Concluído', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Enfermagem em Saúde da Mulher', 'Concluído', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Enfermagem em Saúde Mental', 'Concluído', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Cardiologia e Hemodinâmica', 'Em andamento', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Enfermagem em Prevenção e Controle de Infecção Hospitalar', 'Em andamento', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Enfermagem em Unidade de Terapia Intensiva (UTI)', 'Em andamento', 'Saúde e bem-estar'),
    ('DANIEL LIRA DIAS', 'Graduação', 'Biologia', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('DANIEL LIRA DIAS', 'Mestrado', 'Ciências da Sáude', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('DANIEL LIRA DIAS', 'Graduação', 'Biomedicina', 'Concluído', 'Saúde e bem-estar'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Análise e Desenvolvimento de Sistemas', 'Concluído', 'Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Sistemas de Informação', 'Em andamento', 'Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Design Instrucional', 'Em andamento', 'Educação'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Gestão Escolar', 'Concluído', 'Educação'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Neuropsicopedagogia', 'Em andamento', 'Educação'),
    ('EVELYNE LOPES FERREIRA', 'Graduação', 'Engenharia de Controle e Automação', 'Concluído', 'Engenharia, produção e construção'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Engenharia de Sistemas', 'Concluído', 'Engenharia, produção e construção'),
    ('EVELYNE LOPES FERREIRA', 'Mestrado', 'Engenharia Elétrica (ênfase em IA)', 'Concluído', 'Engenharia, produção e construção'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Gestão Estratégica de Negócios', 'Concluído', 'Negócios, administração e direito'),
    ('FLAVIA DE JESUS NEIVA SAMPAIO', 'Especialização', 'Futuros Acadêmicos e Curriculos Integrados', 'Em andamento', 'Educação'),
    ('FLAVIA DE JESUS NEIVA SAMPAIO', 'Especialização', 'Gestão Ambiental', 'Em andamento', 'Engenharia, produção e construção'),
    ('FLAVIA DE JESUS NEIVA SAMPAIO', 'Graduação', 'Fonoaudiologia', 'Concluído', 'Saúde e bem-estar'),
    ('FLAVIA DE JESUS NEIVA SAMPAIO', 'Mestrado', 'Saúde da Família', 'Concluído', 'Saúde e bem-estar'),
    ('FLAVIA DE JESUS NEIVA SAMPAIO', 'Doutorado', 'Saúde da Família', 'Concluído', 'Saúde e bem-estar'),
    ('GIULIANO PEREIRA DE BARROS', 'Graduação', 'Medicina Veterinária', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('GIULIANO PEREIRA DE BARROS', 'Mestrado', 'Agroecossistemas', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('GIULIANO PEREIRA DE BARROS', 'Doutorado', 'Agroecossistemas', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('GIULIANO PEREIRA DE BARROS', 'Graduação', 'Formação Pedagógica para professores para Educação Profissional', 'Concluído', 'Educação'),
    ('GIULIANO PEREIRA DE BARROS', 'Especialização', 'Homeopatia', 'Em andamento', 'Saúde e bem-estar'),
    ('GIULIANO RICHARDS RIBEIRO', 'Graduação', 'Sistemas de Informação', 'Concluído', 'Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('GIULIANO RICHARDS RIBEIRO', 'Especialização', 'MBA em Desenvolvimento e Análise de Sistemas', 'Concluído', 'Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('GIULIANO RICHARDS RIBEIRO', 'Mestrado', 'Educação Tecnológica', 'Concluído', 'Educação'),
    ('GIULIANO RICHARDS RIBEIRO', 'Especialização', 'MBA em Gestão de Projetos', 'Concluído', 'Negócios, administração e direito'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Graduação', 'Arquitetura e Urbanismo', 'Concluído', 'Engenharia, produção e construção'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Graduação', 'Engenharia Civil', 'Concluído', 'Engenharia, produção e construção'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Especialização', 'Engenharia de Segurança do Trabalho', 'Concluído', 'Engenharia, produção e construção'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Especialização', 'Estruturas de Concreto e Fundações', 'Concluído', 'Engenharia, produção e construção'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Mestrado', 'Arquitetura, Projeto e Meio Ambiente', 'Concluído', 'Engenharia, produção e construção'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Doutorado', 'Arquitetura e Urbanismo', 'Em andamento', 'Engenharia, produção e construção'),
    ('MARCELO LABRE DE MEDEIROS', 'Graduação', 'Pedagogia', 'Em andamento', 'Educação'),
    ('MARCELO LABRE DE MEDEIROS', 'Mestrado', 'Administração', 'Concluído', 'Negócios, administração e direito'),
    ('MARCELO LABRE DE MEDEIROS', 'Graduação', 'Turismo (Bacharelado)', 'Concluído', 'Serviços'),
    ('MARCELO LABRE DE MEDEIROS', 'Especialização', 'Gestão Gastronômica', 'Concluído', 'Serviços'),
    ('MARCILENE PEREIRA DA SILVA', 'Graduação', 'Administração', 'Concluído', 'Negócios, administração e direito'),
    ('MARCILENE PEREIRA DA SILVA', 'Graduação', 'Ciências Contábeis', 'Concluído', 'Negócios, administração e direito'),
    ('MARCILENE PEREIRA DA SILVA', 'Especialização', 'Controladoria e Auditoria', 'Concluído', 'Negócios, administração e direito'),
    ('MARCILENE PEREIRA DA SILVA', 'Mestrado', 'Ciências Contábeis', 'Concluído', 'Negócios, administração e direito'),
    ('NILMAR FRANCISCO DA SILVA SANTOS', 'Especialização', 'Futuros Acadêmicos e Curriculos Integrados', 'Concluído', 'Educação'),
    ('NILMAR FRANCISCO DA SILVA SANTOS', 'Graduação', 'Serviço Social', 'Concluído', 'Saúde e bem-estar'),
    ('NILMAR FRANCISCO DA SILVA SANTOS', 'Mestrado', 'Serviço Social', 'Concluído', 'Saúde e bem-estar'),
    ('NILMAR FRANCISCO DA SILVA SANTOS', 'Doutorado', 'Serviço Social', 'Concluído', 'Saúde e bem-estar'),
    ('SAMANTHA ORQUELITA DE OLIVEIRA BORGES', 'Mestrado', 'Letras – Estudos Literários', 'Concluído', 'Artes e humanidades'),
    ('SAMANTHA ORQUELITA DE OLIVEIRA BORGES', 'Doutorado', 'Letras – Estudos Literários', 'Concluído', 'Artes e humanidades'),
    ('SAMANTHA ORQUELITA DE OLIVEIRA BORGES', 'Pós-doutorado', 'Letras – Literatura, Comparatismo e Crítica Social', 'Concluído', 'Artes e humanidades'),
    ('SAMANTHA ORQUELITA DE OLIVEIRA BORGES', 'Graduação', 'Jornalismo (Comunicação Social)', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('SUELLEN FONSECA SANTOS', 'Mestrado', 'Engenharia Mecânica', 'Concluído', 'Engenharia, produção e construção'),
    ('SUELLEN FONSECA SANTOS', 'Doutorado', 'Bioengenharia', 'Concluído', 'Engenharia, produção e construção'),
    ('SUELLEN FONSECA SANTOS', 'Graduação', 'Fisioterapia', 'Concluído', 'Saúde e bem-estar'),
    ('SUELLEN FONSECA SANTOS', 'Especialização', 'Fisioterapia Dermatofuncional', 'Concluído', 'Saúde e bem-estar'),
    ('RENATO LUIZ VIEIRA DE CARVALHO', 'Graduação', 'Administração', 'Concluído', 'Negócios, administração e direito'),
    ('RENATO LUIZ VIEIRA DE CARVALHO', 'Mestrado', 'Tecnologia e Gestão em Educação a Distância', 'Concluído', 'Educação'),
    ('MURILO DE ASSIS ALFAIX MELO', 'Graduação', 'Psicologia', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('MURILO DE ASSIS ALFAIX MELO', 'Mestrado', 'Ciências do Comportamento', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('FLAVIA MOURE SIMOES DE BRANCO', 'Graduação', 'Nutrição', 'Concluído', 'Saúde e bem-estar'),
    ('FLAVIA MOURE SIMOES DE BRANCO', 'Mestrado', 'Ciências da Saúde', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('FLAVIA MOURE SIMOES DE BRANCO', 'Doutorado', 'Ciências da Saúde', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('MARCOS DONIZETE DA SILVA', 'Graduação', 'Medicina Veterinária', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('MARCOS DONIZETE DA SILVA', 'Especialização', 'Animal Production', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('MARCOS DONIZETE DA SILVA', 'Mestrado', 'Ciencia Animal e Pastagem', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('MARCOS DONIZETE DA SILVA', 'Doutorado', 'Ciencia Animal e Pastagem', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária')
),
ids AS (
  SELECT DISTINCT e.id
  FROM public.nq_especialistas e
  JOIN dados d
    ON lower(trim(e.professor)) = lower(trim(d.professor))
)
DELETE FROM public.nq_especialistas_diplomas
WHERE especialista_id IN (SELECT id FROM ids);

WITH dados(professor, nivel, curso_titulo, situacao, area_cine) AS (
  VALUES
    ('ADRIANO RODRIGUES TEIXEIRA', 'Graduação', 'Matemática', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('ADRIANO RODRIGUES TEIXEIRA', 'Especialização', 'Matemática Pura', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('ADRIANO RODRIGUES TEIXEIRA', 'Mestrado', 'Matemática (profissional)', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('ADRIANO RODRIGUES TEIXEIRA', 'Graduação', 'Física (Licenciatura)', 'Concluído', 'Educação'),
    ('ADRIANO RODRIGUES TEIXEIRA', 'Especialização', 'Gestão de Pessoas', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Graduação', 'Psicologia', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Neuropsicologia', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Psicologia Organizacional', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Futuros Acadêmicos e Currículos Integrados', 'Em andamento', 'Educação'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Graduação', 'Direito', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Recursos Ambientais e Poluição', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Direito Militar', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Perícia Criminal e Judicial', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Especialização', 'Direito Médico e Saúde', 'Concluído', 'Negócios, administração e direito'),
    ('ALEXIA SOARES MONTINGELLI LOPES', 'Mestrado', 'Psicologia Forense', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Tecnologia em Informática e Gestão da Informação', 'Concluído', 'Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Ciência da Computação (Licenciatura)', 'Concluído', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Pedagogia', 'Concluído', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Coordenação Pedagógica para a Educação Básica', 'Concluído', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Docência do Ensino Superior', 'Concluído', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Docência e Tutoria em EAD', 'Concluído', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Sociologia Licenciatura', 'Em andamento', 'Educação'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Tecnologia em Saneamento Ambiental', 'Concluído', 'Engenharia, produção e construção'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Engenharia de Produção', 'Em andamento', 'Engenharia, produção e construção'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Administração', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Ciências Contábeis', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Direito', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Graduação', 'Gestão Comercial', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Advocacia da Fazenda Pública', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Auditoria e Compliance', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Controle Interno na Administração Pública', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Administrativo com Ênfase em Carreiras de Tribunais', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Constitucional Aplicado', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Desportivo Aplicado', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito do Consumidor', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito do Trabalho e Processual do Trabalho', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Imobiliário', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Internacional', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Privado', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direito Público', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Direitos Humanos', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Executivo em Gestão de Pessoas & Coaching', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Gestão de Cidades', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Gestão Empresarial', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Gestão Estratégica da Administração Pública', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Gestão Pública Municipal', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Planejamento Patrimonial, Familiar e Sucessório', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Planejamento Previdenciário', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Planejamento Tributário', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Especialização', 'Advocacia Extrajudicial', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Mestrado', 'Sociedade, Tecnologias e Politicas Públicas', 'Concluído', 'Negócios, administração e direito'),
    ('ANTONIO DA CONCEICAO MENESES JUNIOR', 'Doutorado', 'Desenvolvimento e Meio Ambiente', 'Em andamento', 'Negócios, administração e direito'),
    ('CARLOS PEREIRA MARTINS', 'Mestrado', 'Neurociências', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('CARLOS PEREIRA MARTINS', 'Doutorado', 'Neurociências', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Gestão Pública na Educação Profissional e Tecnológica', 'Concluído', 'Negócios, administração e direito'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Auditoria em Serviços de Saúde', 'Em andamento', 'Negócios, administração e direito'),
    ('CARLOS PEREIRA MARTINS', 'Graduação', 'Enfermagem (Bacharelado)', 'Concluído', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Urgência e Emergência', 'Concluído', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Enfermagem na Atenção Primária com Ênfase na Estratégia Saúde da Família', 'Concluído', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Enfermagem em Saúde da Mulher', 'Concluído', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Enfermagem em Saúde Mental', 'Concluído', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Cardiologia e Hemodinâmica', 'Em andamento', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Enfermagem em Prevenção e Controle de Infecção Hospitalar', 'Em andamento', 'Saúde e bem-estar'),
    ('CARLOS PEREIRA MARTINS', 'Especialização', 'Enfermagem em Unidade de Terapia Intensiva (UTI)', 'Em andamento', 'Saúde e bem-estar'),
    ('DANIEL LIRA DIAS', 'Graduação', 'Biologia', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('DANIEL LIRA DIAS', 'Mestrado', 'Ciências da Sáude', 'Concluído', 'Ciências naturais, matemática e estatística'),
    ('DANIEL LIRA DIAS', 'Graduação', 'Biomedicina', 'Concluído', 'Saúde e bem-estar'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Análise e Desenvolvimento de Sistemas', 'Concluído', 'Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Sistemas de Informação', 'Em andamento', 'Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Design Instrucional', 'Em andamento', 'Educação'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Gestão Escolar', 'Concluído', 'Educação'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Neuropsicopedagogia', 'Em andamento', 'Educação'),
    ('EVELYNE LOPES FERREIRA', 'Graduação', 'Engenharia de Controle e Automação', 'Concluído', 'Engenharia, produção e construção'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Engenharia de Sistemas', 'Concluído', 'Engenharia, produção e construção'),
    ('EVELYNE LOPES FERREIRA', 'Mestrado', 'Engenharia Elétrica (ênfase em IA)', 'Concluído', 'Engenharia, produção e construção'),
    ('EVELYNE LOPES FERREIRA', 'Especialização', 'Gestão Estratégica de Negócios', 'Concluído', 'Negócios, administração e direito'),
    ('FLAVIA DE JESUS NEIVA SAMPAIO', 'Especialização', 'Futuros Acadêmicos e Curriculos Integrados', 'Em andamento', 'Educação'),
    ('FLAVIA DE JESUS NEIVA SAMPAIO', 'Especialização', 'Gestão Ambiental', 'Em andamento', 'Engenharia, produção e construção'),
    ('FLAVIA DE JESUS NEIVA SAMPAIO', 'Graduação', 'Fonoaudiologia', 'Concluído', 'Saúde e bem-estar'),
    ('FLAVIA DE JESUS NEIVA SAMPAIO', 'Mestrado', 'Saúde da Família', 'Concluído', 'Saúde e bem-estar'),
    ('FLAVIA DE JESUS NEIVA SAMPAIO', 'Doutorado', 'Saúde da Família', 'Concluído', 'Saúde e bem-estar'),
    ('GIULIANO PEREIRA DE BARROS', 'Graduação', 'Medicina Veterinária', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('GIULIANO PEREIRA DE BARROS', 'Mestrado', 'Agroecossistemas', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('GIULIANO PEREIRA DE BARROS', 'Doutorado', 'Agroecossistemas', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('GIULIANO PEREIRA DE BARROS', 'Graduação', 'Formação Pedagógica para professores para Educação Profissional', 'Concluído', 'Educação'),
    ('GIULIANO PEREIRA DE BARROS', 'Especialização', 'Homeopatia', 'Em andamento', 'Saúde e bem-estar'),
    ('GIULIANO RICHARDS RIBEIRO', 'Graduação', 'Sistemas de Informação', 'Concluído', 'Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('GIULIANO RICHARDS RIBEIRO', 'Especialização', 'MBA em Desenvolvimento e Análise de Sistemas', 'Concluído', 'Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('GIULIANO RICHARDS RIBEIRO', 'Mestrado', 'Educação Tecnológica', 'Concluído', 'Educação'),
    ('GIULIANO RICHARDS RIBEIRO', 'Especialização', 'MBA em Gestão de Projetos', 'Concluído', 'Negócios, administração e direito'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Graduação', 'Arquitetura e Urbanismo', 'Concluído', 'Engenharia, produção e construção'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Graduação', 'Engenharia Civil', 'Concluído', 'Engenharia, produção e construção'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Especialização', 'Engenharia de Segurança do Trabalho', 'Concluído', 'Engenharia, produção e construção'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Especialização', 'Estruturas de Concreto e Fundações', 'Concluído', 'Engenharia, produção e construção'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Mestrado', 'Arquitetura, Projeto e Meio Ambiente', 'Concluído', 'Engenharia, produção e construção'),
    ('JUAREZ DE QUADROS BARBOSA JUNIOR', 'Doutorado', 'Arquitetura e Urbanismo', 'Em andamento', 'Engenharia, produção e construção'),
    ('MARCELO LABRE DE MEDEIROS', 'Graduação', 'Pedagogia', 'Em andamento', 'Educação'),
    ('MARCELO LABRE DE MEDEIROS', 'Mestrado', 'Administração', 'Concluído', 'Negócios, administração e direito'),
    ('MARCELO LABRE DE MEDEIROS', 'Graduação', 'Turismo (Bacharelado)', 'Concluído', 'Serviços'),
    ('MARCELO LABRE DE MEDEIROS', 'Especialização', 'Gestão Gastronômica', 'Concluído', 'Serviços'),
    ('MARCILENE PEREIRA DA SILVA', 'Graduação', 'Administração', 'Concluído', 'Negócios, administração e direito'),
    ('MARCILENE PEREIRA DA SILVA', 'Graduação', 'Ciências Contábeis', 'Concluído', 'Negócios, administração e direito'),
    ('MARCILENE PEREIRA DA SILVA', 'Especialização', 'Controladoria e Auditoria', 'Concluído', 'Negócios, administração e direito'),
    ('MARCILENE PEREIRA DA SILVA', 'Mestrado', 'Ciências Contábeis', 'Concluído', 'Negócios, administração e direito'),
    ('NILMAR FRANCISCO DA SILVA SANTOS', 'Especialização', 'Futuros Acadêmicos e Curriculos Integrados', 'Concluído', 'Educação'),
    ('NILMAR FRANCISCO DA SILVA SANTOS', 'Graduação', 'Serviço Social', 'Concluído', 'Saúde e bem-estar'),
    ('NILMAR FRANCISCO DA SILVA SANTOS', 'Mestrado', 'Serviço Social', 'Concluído', 'Saúde e bem-estar'),
    ('NILMAR FRANCISCO DA SILVA SANTOS', 'Doutorado', 'Serviço Social', 'Concluído', 'Saúde e bem-estar'),
    ('SAMANTHA ORQUELITA DE OLIVEIRA BORGES', 'Mestrado', 'Letras – Estudos Literários', 'Concluído', 'Artes e humanidades'),
    ('SAMANTHA ORQUELITA DE OLIVEIRA BORGES', 'Doutorado', 'Letras – Estudos Literários', 'Concluído', 'Artes e humanidades'),
    ('SAMANTHA ORQUELITA DE OLIVEIRA BORGES', 'Pós-doutorado', 'Letras – Literatura, Comparatismo e Crítica Social', 'Concluído', 'Artes e humanidades'),
    ('SAMANTHA ORQUELITA DE OLIVEIRA BORGES', 'Graduação', 'Jornalismo (Comunicação Social)', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('SUELLEN FONSECA SANTOS', 'Mestrado', 'Engenharia Mecânica', 'Concluído', 'Engenharia, produção e construção'),
    ('SUELLEN FONSECA SANTOS', 'Doutorado', 'Bioengenharia', 'Concluído', 'Engenharia, produção e construção'),
    ('SUELLEN FONSECA SANTOS', 'Graduação', 'Fisioterapia', 'Concluído', 'Saúde e bem-estar'),
    ('SUELLEN FONSECA SANTOS', 'Especialização', 'Fisioterapia Dermatofuncional', 'Concluído', 'Saúde e bem-estar'),
    ('RENATO LUIZ VIEIRA DE CARVALHO', 'Graduação', 'Administração', 'Concluído', 'Negócios, administração e direito'),
    ('RENATO LUIZ VIEIRA DE CARVALHO', 'Mestrado', 'Tecnologia e Gestão em Educação a Distância', 'Concluído', 'Educação'),
    ('MURILO DE ASSIS ALFAIX MELO', 'Graduação', 'Psicologia', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('MURILO DE ASSIS ALFAIX MELO', 'Mestrado', 'Ciências do Comportamento', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('FLAVIA MOURE SIMOES DE BRANCO', 'Graduação', 'Nutrição', 'Concluído', 'Saúde e bem-estar'),
    ('FLAVIA MOURE SIMOES DE BRANCO', 'Mestrado', 'Ciências da Saúde', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('FLAVIA MOURE SIMOES DE BRANCO', 'Doutorado', 'Ciências da Saúde', 'Concluído', 'Ciências sociais, comunicação e informação'),
    ('MARCOS DONIZETE DA SILVA', 'Graduação', 'Medicina Veterinária', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('MARCOS DONIZETE DA SILVA', 'Especialização', 'Animal Production', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('MARCOS DONIZETE DA SILVA', 'Mestrado', 'Ciencia Animal e Pastagem', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária'),
    ('MARCOS DONIZETE DA SILVA', 'Doutorado', 'Ciencia Animal e Pastagem', 'Concluído', 'Agricultura, silvicultura, pesca e veterinária')
)
INSERT INTO public.nq_especialistas_diplomas
  (especialista_id, nivel, curso_titulo, situacao, area_cine, updated_at)
SELECT
  e.id,
  d.nivel,
  d.curso_titulo,
  d.situacao,
  d.area_cine,
  now()
FROM dados d
JOIN public.nq_especialistas e
  ON lower(trim(e.professor)) = lower(trim(d.professor));

COMMIT;

-- Conferência:
SELECT
  COUNT(*) AS total_formacoes,
  COUNT(*) FILTER (WHERE lower(coalesce(situacao,'')) LIKE '%conclu%') AS concluidas,
  COUNT(*) FILTER (WHERE lower(coalesce(situacao,'')) LIKE '%andamento%') AS em_andamento,
  COUNT(DISTINCT area_cine) FILTER (
    WHERE area_cine IS NOT NULL AND trim(area_cine) <> ''
  ) AS areas_cine
FROM public.vw_nq_especialistas_diplomas;

-- Também confira se todos os 19 professores tiveram vínculo:
SELECT
  COUNT(DISTINCT especialista_id) AS professores_com_formacoes
FROM public.vw_nq_especialistas_diplomas;
