-- BI-Monday V25.15 | Formações acadêmicas completas pela aba Diplomas
-- Execute este arquivo UMA VEZ no SQL Editor do Supabase antes de importar a planilha V25.15.

CREATE TABLE IF NOT EXISTS public.nq_especialistas_diplomas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  especialista_id bigint NOT NULL REFERENCES public.nq_especialistas(id) ON DELETE CASCADE,
  nivel text,
  curso_titulo text NOT NULL,
  situacao text,
  area_cine text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_nq_diplomas_especialista
  ON public.nq_especialistas_diplomas(especialista_id);
CREATE INDEX IF NOT EXISTS idx_nq_diplomas_area_cine
  ON public.nq_especialistas_diplomas(area_cine);

ALTER TABLE public.nq_especialistas_diplomas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "nq_diplomas_select_authenticated" ON public.nq_especialistas_diplomas;
CREATE POLICY "nq_diplomas_select_authenticated"
ON public.nq_especialistas_diplomas
FOR SELECT TO authenticated
USING (true);

CREATE OR REPLACE VIEW public.vw_nq_especialistas_diplomas AS
SELECT
  e.id AS especialista_id,
  e.professor,
  e.marca_area_contratante,
  e.marca_origem,
  e.situacao_contratacao,
  d.id AS diploma_id,
  d.nivel,
  d.curso_titulo,
  d.situacao,
  d.area_cine
FROM public.nq_especialistas e
JOIN public.nq_especialistas_diplomas d ON d.especialista_id = e.id
WHERE e.ativo = true;

GRANT SELECT ON public.nq_especialistas_diplomas TO authenticated;
GRANT SELECT ON public.vw_nq_especialistas_diplomas TO authenticated;

-- Conferência após uma nova importação:
SELECT
  COUNT(*) AS total_formacoes,
  COUNT(*) FILTER (WHERE lower(coalesce(situacao,'')) LIKE '%conclu%') AS concluidas,
  COUNT(*) FILTER (WHERE lower(coalesce(situacao,'')) LIKE '%andamento%') AS em_andamento,
  COUNT(DISTINCT area_cine) FILTER (WHERE area_cine IS NOT NULL AND trim(area_cine) <> '') AS areas_cine
FROM public.vw_nq_especialistas_diplomas;
