-- V25.20 | Cadastro oficial de Gestores e Revisores NQ
-- Fonte de apoio: Base NQ + colunas "Gestor de Validação - NQ" e "Revisor Validador".
-- Objetivo: impedir que DA, conteudista e outros papéis entrem nos filtros/KPIs de responsáveis NQ.

create table if not exists public.nq_responsaveis (
  id bigint generated by default as identity primary key,
  nome_oficial text not null unique,
  aliases text[] not null default '{}'::text[],
  emails text[] not null default '{}'::text[],
  eh_gestor boolean not null default false,
  eh_revisor boolean not null default false,
  ativo boolean not null default true,
  origem text,
  observacao text,
  updated_at timestamptz not null default now()
);

alter table public.nq_responsaveis enable row level security;

drop policy if exists "nq_responsaveis_select_authenticated" on public.nq_responsaveis;
create policy "nq_responsaveis_select_authenticated"
on public.nq_responsaveis
for select
to authenticated
using (true);

-- 19 especialistas da Base NQ. Os papéis abaixo refletem o que foi observado
-- no export atual do quadro de Validação de Materiais em 15/09/2026.
insert into public.nq_responsaveis
(nome_oficial, aliases, emails, eh_gestor, eh_revisor, ativo, origem, observacao)
values
('ADRIANO RODRIGUES TEIXEIRA', array['Adriano Rodrigues Teixeira'], array[]::text[], true, true, true, 'Base NQ + Monday', 'Observado como gestor e revisor.'),
('ALEXIA SOARES MONTINGELLI LOPES', array['Alexia Soares Montingelli Lopes'], array['alexia.lopes@ulife.com.br'], true, true, true, 'Base NQ + Monday', 'No Monday aparece principalmente pelo e-mail.'),
('ANTONIO DA CONCEICAO MENESES JUNIOR', array['Antonio da Conceicao Meneses Junior','Antonio da Conceição Meneses Junior'], array['antonio.meneses@ulife.com.br'], true, true, true, 'Base NQ + Monday', 'No Monday aparece também pelo e-mail.'),
('CARLOS PEREIRA MARTINS', array['Carlos Pereira Martins'], array['carlos.p.martins@ulife.com.br'], true, true, true, 'Base NQ + Monday', 'No Monday aparece principalmente pelo e-mail.'),
('DANIEL LIRA DIAS', array['Daniel Lira Dias','DANIEL LIRA DIAS'], array[]::text[], true, true, true, 'Base NQ + Monday', null),
('EVELYNE LOPES FERREIRA', array['Evelyne Ferreira','Evelyne Lopes Ferreira'], array[]::text[], true, true, true, 'Base NQ + Monday', 'Alias reduzido usado no Monday.'),
('FLAVIA DE JESUS NEIVA SAMPAIO', array['Flavia de Jesus Neiva Sampaio','FLAVIA DE JESUS NEIVA SAMPAIO'], array[]::text[], true, true, true, 'Base NQ + Monday', null),
('FLAVIA MOURE SIMOES DE BRANCO', array['Flavia Moure Simoes de Branco','FLAVIA MOURE SIMOES DE BRANCO'], array[]::text[], false, false, true, 'Base NQ', 'Especialista ativo, mas não observado nas colunas de gestor/revisor no export analisado.'),
('GIULIANO PEREIRA DE BARROS', array['Giuliano Barros','Giuliano Pereira de Barros'], array[]::text[], true, true, true, 'Base NQ + Monday', 'Alias reduzido usado no Monday.'),
('GIULIANO RICHARDS RIBEIRO', array['Giuliano Richards Ribeiro'], array[]::text[], true, true, true, 'Base NQ + Monday', null),
('JUAREZ DE QUADROS BARBOSA JUNIOR', array['Juarez de Quadros Barbosa Júnior','Juarez de Quadros Barbosa Junior'], array[]::text[], true, true, true, 'Base NQ + Monday', 'Considera variação com/sem acento.'),
('MARCELO LABRE DE MEDEIROS', array['Marcelo Labre de Medeiros'], array[]::text[], true, true, true, 'Base NQ + Monday', null),
('MARCILENE PEREIRA DA SILVA', array['Marcilene Pereira da Silva'], array[]::text[], true, true, true, 'Base NQ + Monday', null),
('MARCOS DONIZETE DA SILVA', array['Marcos Donizete da Silva','MARCOS DONIZETE DA SILVA'], array[]::text[], false, false, true, 'Base NQ', 'Especialista ativo, mas não observado nas colunas de gestor/revisor no export analisado.'),
('MURILO DE ASSIS ALFAIX MELO', array['Murilo de Assis Alfaix Melo','MURILO DE ASSIS ALFAIX MELO'], array[]::text[], false, false, true, 'Base NQ', 'Especialista ativo, mas não observado nas colunas de gestor/revisor no export analisado.'),
('NILMAR FRANCISCO DA SILVA SANTOS', array['Nilmar Francisco da Silva Santos'], array[]::text[], true, true, true, 'Base NQ + Monday', null),
('RENATO LUIZ VIEIRA DE CARVALHO', array['Renato Luiz Vieira de Carvalho'], array[]::text[], true, true, true, 'Base NQ + Monday', null),
('SAMANTHA ORQUELITA DE OLIVEIRA BORGES', array['Samantha Borges','Samantha Orquelita de Oliveira Borges'], array[]::text[], true, true, true, 'Base NQ + Monday', 'Alias reduzido usado no Monday.'),
('SUELLEN FONSECA SANTOS', array['Suellen Fonseca','Suellen Fonseca Santos'], array[]::text[], true, true, true, 'Base NQ + Monday', 'Alias reduzido usado no Monday.')
on conflict (nome_oficial) do update set
  aliases = excluded.aliases,
  emails = excluded.emails,
  eh_gestor = excluded.eh_gestor,
  eh_revisor = excluded.eh_revisor,
  ativo = excluded.ativo,
  origem = excluded.origem,
  observacao = excluded.observacao,
  updated_at = now();

-- Conferência rápida.
select
  count(*) filter (where ativo) as responsaveis_ativos,
  count(*) filter (where ativo and eh_gestor) as gestores_nq,
  count(*) filter (where ativo and eh_revisor) as revisores_nq
from public.nq_responsaveis;
